# AUTO-GENERATED by .github/workflows/_gen_stubs.py — do not edit by hand.
# Editor-only type stubs for the dynamic dotted namespace. No runtime effect.
# Regenerate: python .github/workflows/_gen_stubs.py

from .core import WIEFile as WIEFile

class _Variable:
    LWalbedo: WIEFile
    SWalbedo: WIEFile
    SoilRH: WIEFile
    acetone: WIEFile
    acetonepft: WIEFile
    albedo: WIEFile
    albedopft: WIEFile
    alt: WIEFile
    burntArea: WIEFile
    burntareaPft: WIEFile
    burntareaTotal: WIEFile
    burntareapeatTotal: WIEFile
    cCwd: WIEFile
    cLeaf: WIEFile
    cLitter: WIEFile
    cLitterpft: WIEFile
    cPoolVr: WIEFile
    cProduct: WIEFile
    cRoot: WIEFile
    cSoil: WIEFile
    cSoilAbove1m: WIEFile
    cSoilBelow1m: WIEFile
    cSoilLayers: WIEFile
    cSoilPools: WIEFile
    cSoilpft: WIEFile
    cVeg: WIEFile
    cVegpft: WIEFile
    cWood: WIEFile
    canopyheightTotal: WIEFile
    ccfuelTotal: WIEFile
    cfuelTotal: WIEFile
    ch4: WIEFile
    docFlux: WIEFile
    evapo: WIEFile
    evapotrans: WIEFile
    evapotranspft: WIEFile
    fAllocLeaf: WIEFile
    fAllocRoot: WIEFile
    fAllocWood: WIEFile
    fBNF: WIEFile
    fCH4Fire: WIEFile
    fFire: WIEFile
    fFireCH4pft: WIEFile
    fFireCOpft: WIEFile
    fFireCsoil: WIEFile
    fFireCveg: WIEFile
    fFireLitter: WIEFile
    fFirepft: WIEFile
    fLeafLitter: WIEFile
    fLitterSoil: WIEFile
    fN2: WIEFile
    fN2O: WIEFile
    fN2OFire: WIEFile
    fN2Odenit: WIEFile
    fN2Onit: WIEFile
    fN2Opft: WIEFile
    fNGraz: WIEFile
    fNH3vol: WIEFile
    fNHarvest: WIEFile
    fNLitterSoil: WIEFile
    fNOx: WIEFile
    fNdenitri: WIEFile
    fNdep: WIEFile
    fNleach: WIEFile
    fNloss: WIEFile
    fNnetmin: WIEFile
    fNnitri: WIEFile
    fNup: WIEFile
    fRootLitter: WIEFile
    fVegLitter: WIEFile
    fVegSoil: WIEFile
    fWoodLitter: WIEFile
    fch4layer: WIEFile
    fch4soil: WIEFile
    fdepth: WIEFile
    ffirech4: WIEFile
    ffirepeatTotal: WIEFile
    firePrescribed: WIEFile
    firedurationTotal: WIEFile
    fireintsTotal: WIEFile
    firemortalityTotal: WIEFile
    firenrTotal: WIEFile
    firenrperc95Total: WIEFile
    firerosTotal: WIEFile
    firesizeTotal: WIEFile
    firesizeperc95Total: WIEFile
    fluch4: WIEFile
    fpar: WIEFile
    fpftch4: WIEFile
    fwetch4: WIEFile
    gpp: WIEFile
    gpppft: WIEFile
    highcoverTotal: WIEFile
    ignlightTotal: WIEFile
    isopr: WIEFile
    isoprpft: WIEFile
    lai: WIEFile
    laipft: WIEFile
    landCoverFrac: WIEFile
    lowcoverTotal: WIEFile
    lwnet: WIEFile
    methanol: WIEFile
    methanolpft: WIEFile
    mfuelTotal: WIEFile
    mrro: WIEFile
    mrso: WIEFile
    mrsoLayer: WIEFile
    nInOrgSoilpft: WIEFile
    nInorgSoil: WIEFile
    nInorgSoilLayer: WIEFile
    nLitter: WIEFile
    nLitterpft: WIEFile
    nOrgSoil: WIEFile
    nOrgSoilLayer: WIEFile
    nOrgSoilpft: WIEFile
    nVeg: WIEFile
    nVegpft: WIEFile
    nbp: WIEFile
    nbppft: WIEFile
    npp: WIEFile
    npppft: WIEFile
    oceanCoverFrac: WIEFile
    pch4: WIEFile
    pco2: WIEFile
    pr: WIEFile
    qair: WIEFile
    qh: WIEFile
    qle: WIEFile
    qsb: WIEFile
    ra: WIEFile
    rainf: WIEFile
    rh: WIEFile
    rhLayers: WIEFile
    rhPools: WIEFile
    rhpft: WIEFile
    rnpft: WIEFile
    rsds: WIEFile
    shflxpft: WIEFile
    snowDepth: WIEFile
    snow_depthpft: WIEFile
    snowf: WIEFile
    soilIce: WIEFile
    soilMoist: WIEFile
    soilR: WIEFile
    soilRh: WIEFile
    soilT: WIEFile
    soilTemp: WIEFile
    soilWet: WIEFile
    sulfApp: WIEFile
    suppressedIgnit: WIEFile
    swalbedo: WIEFile
    swe: WIEFile
    swnet: WIEFile
    tair: WIEFile
    tas: WIEFile
    tcan: WIEFile
    terp: WIEFile
    terppft: WIEFile
    transpft: WIEFile
    tveg: WIEFile
    wetCH4: WIEFile
    wetfrac: WIEFile
    wind: WIEFile
    wtd: WIEFile
    nSoil: WIEFile
    nSoilpft: WIEFile
    def __getattr__(self, name: str) -> WIEFile: ...

class _BiomeE_Factorial:
    baseline: _Variable

class _BiomeE_Simulation:
    bgc: _BiomeE_Factorial
    cou: _BiomeE_Factorial
    rad: _BiomeE_Factorial
    ctrl: _BiomeE_Factorial

class _BiomeE_Forcing:
    ukesm: _BiomeE_Simulation
    ipsl: _BiomeE_Simulation
    gfdl: _BiomeE_Simulation

class _CLASSIC_Factorial:
    baseline: _Variable
    ndep: _Variable
    noFire: _Variable
    noNitrogen: _Variable
    ndep_noFire: _Variable
    noFire_noNitrogen: _Variable

class _CLASSIC_Simulation:
    bgc: _CLASSIC_Factorial
    cou: _CLASSIC_Factorial
    rad: _CLASSIC_Factorial
    ctrl: _CLASSIC_Factorial

class _CLASSIC_Forcing:
    ukesm: _CLASSIC_Simulation
    ipsl: _CLASSIC_Simulation
    gfdl: _CLASSIC_Simulation

class _DLEM_Factorial:
    baseline: _Variable
    noNdep: _Variable

class _DLEM_Simulation:
    bgc: _DLEM_Factorial
    cou: _DLEM_Factorial
    rad: _DLEM_Factorial
    ctrl: _DLEM_Factorial

class _DLEM_Forcing:
    ukesm: _DLEM_Simulation
    ipsl: _DLEM_Simulation
    gfdl: _DLEM_Simulation

class _JSBACH_Factorial:
    baseline: _Variable
    ndep: _Variable
    noNitrogen: _Variable

class _JSBACH_Simulation:
    bgc: _JSBACH_Factorial
    cou: _JSBACH_Factorial
    rad: _JSBACH_Factorial
    ctrl: _JSBACH_Factorial

class _JSBACH_Forcing:
    ukesm: _JSBACH_Simulation
    ipsl: _JSBACH_Simulation
    gfdl: _JSBACH_Simulation

class _JULES_Factorial:
    baseline: _Variable
    noNitrogen: _Variable
    noDynVeg: _Variable
    noPermafrostC: _Variable
    noPermafrostCN: _Variable
    noPermafrostCNNinorg: _Variable
    addPermafrostC: _Variable
    addPermafrostCN: _Variable
    addPermafrostCNNinorg: _Variable
    noNitrogen_addPermafrostC: _Variable
    noNitrogen_noPermafrostC: _Variable
    Fire0005: _Variable
    Fire0249: _Variable
    Fire0304: _Variable
    Fire0336: _Variable

class _JULES_Simulation:
    bgc: _JULES_Factorial
    cou: _JULES_Factorial
    rad: _JULES_Factorial
    ctrl: _JULES_Factorial

class _JULES_Forcing:
    ukesm: _JULES_Simulation
    ipsl: _JULES_Simulation
    gfdl: _JULES_Simulation

class _LPX_Bern_Factorial:
    baseline: _Variable
    nofire: _Variable
    nopermafrost: _Variable
    nopermafrost_nofire: _Variable
    ndep: _Variable

class _LPX_Bern_Simulation:
    bgc: _LPX_Bern_Factorial
    cou: _LPX_Bern_Factorial
    rad: _LPX_Bern_Factorial
    ctrl: _LPX_Bern_Factorial

class _LPX_Bern_Forcing:
    ukesm: _LPX_Bern_Simulation
    ipsl: _LPX_Bern_Simulation
    gfdl: _LPX_Bern_Simulation

class _VISIT_UT_Factorial:
    baseline: _Variable
    noBVOC: _Variable
    noFire: _Variable

class _VISIT_UT_Simulation:
    bgc: _VISIT_UT_Factorial
    cou: _VISIT_UT_Factorial
    rad: _VISIT_UT_Factorial
    ctrl: _VISIT_UT_Factorial

class _VISIT_UT_Forcing:
    ukesm: _VISIT_UT_Simulation
    ipsl: _VISIT_UT_Simulation
    gfdl: _VISIT_UT_Simulation

class _Model:
    BiomeE: _BiomeE_Forcing
    CLASSIC: _CLASSIC_Forcing
    DLEM: _DLEM_Forcing
    JSBACH: _JSBACH_Forcing
    JULES: _JULES_Forcing
    LPX_Bern: _LPX_Bern_Forcing
    VISIT_UT: _VISIT_UT_Forcing

# top-level iterables over the axis vocabularies
models: tuple[str, ...]
variables: tuple[str, ...]
gcm_patterns: tuple[str, ...]
simulations: tuple[str, ...]

# experiment axis (module level)
one_percent_co2: _Model
overshoot: _Model

__all__: list[str]
