"""Generate `wiemip_registry/__init__.pyi` so editors (Pylance / PyCharm) can
autocomplete the dynamic dotted namespace
(`wr.one_percent_co2.LPX_Bern.ukesm.bgc.baseline.cVeg`).

The namespace is resolved at runtime via `__getattr__`, which static analyzers
cannot follow — so we hand them a stub describing the axis chain. Re-run this
whenever the enums in `const.py` or the model list change:

    python wiemip_registry/_gen_stubs.py

It only reads `const.py` (stdlib only — no xarray needed) and writes the `.pyi`.
Stub files are never imported at runtime, so this has ZERO effect on behaviour.
"""
from __future__ import annotations

import importlib.util
from pathlib import Path

_HERE = Path(__file__).resolve().parent


def _load_const():
    """Load const.py standalone, bypassing the package __init__ (and its deps)."""
    spec = importlib.util.spec_from_file_location("_wr_const", _HERE / "const.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _class(name: str, attrs: list[str], value_type: str, getattr_type: str | None = None) -> str:
    lines = [f"class {name}:"]
    lines += [f"    {a}: {value_type}" for a in attrs]
    if getattr_type:
        lines.append(f"    def __getattr__(self, name: str) -> {getattr_type}: ...")
    if len(lines) == 1:                       # no body emitted
        lines.append("    ...")
    return "\n".join(lines)


def build_stub() -> str:
    const = _load_const()
    experiments = [m.name for m in const.Experiment]
    parts = [
        "# AUTO-GENERATED by wiemip_registry/_gen_stubs.py — do not edit by hand.",
        "# Editor-only type stubs for the dynamic dotted namespace. No runtime effect.",
        "# Regenerate after changing const.py: python wiemip_registry/_gen_stubs.py",
        "",
        "from .core import WIEFile as WIEFile",
        "",
        _class("_Variable", list(const.VARIABLES), "WIEFile", getattr_type="WIEFile"),
        "",
        _class("_Factorial", [m.name for m in const.Factorial], "_Variable"),
        "",
        _class("_Simulation", [m.name for m in const.Simulation], "_Factorial"),
        "",
        _class("_Forcing", [m.name for m in const.GCMPattern], "_Simulation"),
        "",
        _class("_Model", list(const.MODEL_PACKAGES), "_Forcing"),
        "",
        "# top-level iterables over the axis vocabularies",
        "models: tuple[str, ...]",
        "variables: tuple[str, ...]",
        "gcm_patterns: tuple[str, ...]",
        "simulations: tuple[str, ...]",
        "",
        "# experiment axis (module level)",
        *[f"{e}: _Model" for e in experiments],
        "",
        '__all__: list[str]',
        "",
    ]
    return "\n".join(parts)


def main() -> None:
    out = _HERE / "__init__.pyi"
    out.write_text(build_stub())
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
