"""Generate `wiemip_registry/__init__.pyi` so editors (Pylance / PyCharm / jedi) can
autocomplete the dynamic dotted namespace
(`wr.one_percent_co2.LPX_Bern.ukesm.bgc.baseline.cVeg`).

The namespace is resolved at runtime via `__getattr__`, which static analyzers can't
follow — so we hand them a stub describing the axis chain. Each model gets its OWN
factorial → simulation → forcing subtree, built from that adapter's `FACTORIALS`, so
the factorial axis autocompletes per-model (CLASSIC offers noFire/noNitrogen/…, LPX
offers nofire/nopermafrost/…, etc.). The variable leaf is `wr.variables`, which
already merges `variables.py` (the data request) with `variable_overrides.py`
(superseded-but-uploaded names) — so overrides show up here too.

This imports the package (needs its deps, e.g. xarray) to read the live adapters —
no S3 / mounted bucket required, just an importable env. Stub files are never imported
at runtime, so this has ZERO effect on behaviour.

Re-run after the enums / models / variables / any adapter's FACTORIALS change (the
sync script chains it):

    python .github/workflows/_gen_stubs.py
"""
from __future__ import annotations

import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent          # <repo>/.github/workflows
_REPO = _HERE.parents[1]                           # <repo>
_PKG = _REPO / "wiemip_registry"


def _class(name: str, attrs: list[str], value_type: str, getattr_type: str | None = None) -> str:
    lines = [f"class {name}:"]
    lines += [f"    {a}: {value_type}" for a in attrs]
    if getattr_type:
        lines.append(f"    def __getattr__(self, name: str) -> {getattr_type}: ...")
    if len(lines) == 1:                       # no body emitted
        lines.append("    ...")
    return "\n".join(lines)


def build_stub() -> str:
    sys.path.insert(0, str(_REPO))            # make `wiemip_registry` importable in-place
    import wiemip_registry as wr
    from wiemip_registry import const

    variables = list(wr.variables)            # data-request list + variable_overrides
    sims = [m.name for m in const.Simulation]
    forcings = [m.name for m in const.GCMPattern]
    experiments = [m.name for m in const.Experiment]
    models = list(wr.models)

    parts = [
        "# AUTO-GENERATED by .github/workflows/_gen_stubs.py — do not edit by hand.",
        "# Editor-only type stubs for the dynamic dotted namespace. No runtime effect.",
        "# Regenerate: python .github/workflows/_gen_stubs.py",
        "",
        "from .core import WIEFile as WIEFile",
        "",
        # Variable leaf is shared and free-form (any name resolves) -> __getattr__ fallback.
        _class("_Variable", variables, "WIEFile", getattr_type="WIEFile"),
        "",
    ]

    # Per-model factorial -> simulation -> forcing subtrees, so each model autocompletes
    # only its own factorials (validated axis: no __getattr__ fallback on _Factorial).
    for name in models:
        factorials = list(wr._ADAPTERS[name].FACTORIALS)
        parts += [
            _class(f"_{name}_Factorial", factorials, "_Variable"),
            "",
            _class(f"_{name}_Simulation", sims, f"_{name}_Factorial"),
            "",
            _class(f"_{name}_Forcing", forcings, f"_{name}_Simulation"),
            "",
        ]

    # _Model: each model points at its own _Forcing subtree (per-attr type).
    parts += ["class _Model:"]
    parts += [f"    {name}: _{name}_Forcing" for name in models]
    parts += [
        "",
        "# top-level iterables over the axis vocabularies",
        "models: tuple[str, ...]",
        "variables: tuple[str, ...]",
        "gcm_patterns: tuple[str, ...]",
        "simulations: tuple[str, ...]",
        "",
        "# experiment axis (module level)",
        *[f"{e}: _Model" for e in experiments],
        "",
        "__all__: list[str]",
        "",
    ]
    return "\n".join(parts)


def main() -> None:
    out = _PKG / "__init__.pyi"
    out.write_text(build_stub())
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
