"""Generate `wiemip_registry/__init__.pyi` so editors (Pylance / PyCharm / jedi) can
autocomplete the dynamic dotted namespace
(`wr.one_percent_co2.LPX_Bern.ukesm.bgc.baseline.cVeg`).

The namespace is resolved at runtime via `__getattr__`, which static analyzers can't
follow — so we hand them a stub describing the axis chain. It reads the enums + model
list from `wiemip_registry/const.py` and the variable list from
`wiemip_registry/variables.py`, both loaded standalone (stdlib only — no xarray). Stub
files are never imported at runtime, so this has ZERO effect on behaviour.

Re-run after the enums / model list / variable list change (the sync script chains it):

    python .github/workflows/_gen_stubs.py
"""
from __future__ import annotations

import importlib.util
from pathlib import Path

_HERE = Path(__file__).resolve().parent          # <repo>/.github/workflows
_PKG = _HERE.parents[1] / "wiemip_registry"       # <repo>/wiemip_registry


def _load(name: str, path: Path):
    """Load a module standalone (no package import / heavy deps)."""
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _class(name: str, attrs: list[str], value_type: str, getattr_type: str | None = None) -> str:
    lines = [f"class {name}:"]
    lines += [f"    {a}: {value_type}" for a in attrs]
    if getattr_type:
        lines.append(f"    def __getattr__(self, name: str) -> {getattr_type}: ...")
    if len(lines) == 1:                       # no body emitted
        lines.append("    ...")
    return "\n".join(lines)


def build_stub() -> str:
    const = _load("_wr_const", _PKG / "const.py")
    variables = _load("_wr_variables", _PKG / "variables.py")
    experiments = [m.name for m in const.Experiment]
    parts = [
        "# AUTO-GENERATED by .github/workflows/_gen_stubs.py — do not edit by hand.",
        "# Editor-only type stubs for the dynamic dotted namespace. No runtime effect.",
        "# Regenerate: python .github/workflows/_gen_stubs.py",
        "",
        "from .core import WIEFile as WIEFile",
        "",
        _class("_Variable", list(variables.VARIABLES), "WIEFile", getattr_type="WIEFile"),
        "",
        _class("_Factorial", [m.name for m in const.Factorial], "_Variable"),
        "",
        _class("_Simulation", [m.name for m in const.Simulation], "_Factorial"),
        "",
        _class("_Forcing", [m.name for m in const.GCMPattern], "_Simulation"),
        "",
        _class("_Model", list(const.MODEL_PACKAGES), "_Forcing"),
        "",
        "# top-level iterables over the axis vocabularies",
        "models: tuple[str, ...]",
        "variables: tuple[str, ...]",
        "gcm_patterns: tuple[str, ...]",
        "simulations: tuple[str, ...]",
        "",
        "# experiment axis (module level)",
        *[f"{e}: _Model" for e in experiments],
        "",
        "__all__: list[str]",
        "",
    ]
    return "\n".join(parts)


def main() -> None:
    out = _PKG / "__init__.pyi"
    out.write_text(build_stub())
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
