"""Sync `wiemip_registry`'s variable list from the WIE-MIP data request
(GitHub: colligant/wiemip-data-request) into `wiemip_registry/variables.py`, then
regenerate `__init__.pyi` so `wr.variables` and editor autocomplete track it.

The data request defines one JSON per variable under
`<data-request>/variables/<category>/<name>.json`, each carrying a `"Variable name"`
short/CMIP name. This collects those names across all categories and overwrites
`variables.py`. Run by the `sync-variables` GitHub Action, or by hand:

    python .github/workflows/_sync_variables.py
    python .github/workflows/_sync_variables.py /path/to/wiemip-data-request
    WIEMIP_DATA_REQUEST=/path/to/wiemip-data-request python .github/workflows/_sync_variables.py

The sync itself is stdlib (json + pathlib), but it chains `_gen_stubs.py`, which now
imports `wiemip_registry` (to read each adapter's per-model FACTORIALS), so the stub
step needs the package's deps installed. The synced `variables.py` is COMMITTED, so
using the package needs no data-request checkout — only re-syncing does. If the data
request is ever added as a git submodule at the repo root it's picked up automatically
(it's one of the search candidates), no code change needed.
"""
from __future__ import annotations

import importlib.util
import json
import os
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent           # <repo>/.github/workflows
_REPO = _HERE.parents[1]                            # <repo>
_PKG = _REPO / "wiemip_registry"
_VARIABLES_PY = _PKG / "variables.py"


def _candidate_roots(explicit: str | None) -> list[Path]:
    """Where to look for the data-request repo. An explicit arg/env is authoritative
    (no silent fallback, so typos surface); otherwise try the in-tree submodule then
    the sibling clone."""
    explicit = explicit or os.environ.get("WIEMIP_DATA_REQUEST")
    if explicit:
        return [Path(explicit).expanduser()]
    return [
        _REPO / "wiemip-data-request",          # in-tree submodule
        _REPO.parent / "wiemip-data-request",   # sibling clone
    ]


def _find_variables_dir(explicit: str | None) -> Path:
    """Resolve the data request's `variables/` dir (accepts the repo root or that dir)."""
    roots = _candidate_roots(explicit)
    for root in roots:
        cand = root if root.name == "variables" else root / "variables"
        if cand.is_dir():
            return cand
    tried = "\n  ".join(str(r) for r in roots)
    raise SystemExit(
        "Could not find the wiemip-data-request `variables/` directory. Tried:\n  "
        f"{tried}\n"
        "Clone colligant/wiemip-data-request next to this repo, pass its path as an "
        "argument, or set $WIEMIP_DATA_REQUEST."
    )


def collect_variables(variables_dir: Path) -> list[str]:
    """Sorted, de-duplicated `Variable name`s across every category JSON."""
    names: set[str] = set()
    for jf in sorted(variables_dir.rglob("*.json")):
        with jf.open(encoding="utf-8") as fh:
            data = json.load(fh)
        name = (data.get("Variable name") or "").strip()
        if name:
            names.add(name)
    if not names:
        raise SystemExit(f"No `Variable name` entries found under {variables_dir}.")
    return sorted(names)


def write_variables_py(names: list[str]) -> None:
    body = "\n".join(f'    "{n}",' for n in names)
    _VARIABLES_PY.write_text(
        "# AUTO-GENERATED by .github/workflows/_sync_variables.py — do not edit by hand.\n"
        "# Variable short-names from the WIE-MIP data request (colligant/wiemip-data-request).\n"
        "# Regenerate: python .github/workflows/_sync_variables.py\n"
        "#\n"
        "# The `variable` axis is free-form (any name resolves, erroring only at read if the\n"
        "# file is absent) — this list is for iteration / completion, NOT a gating schema.\n"
        f"VARIABLES = [\n{body}\n]\n"
    )


def _regenerate_stubs() -> None:
    """Re-run _gen_stubs.main() so __init__.pyi / wr.variables track the new list."""
    spec = importlib.util.spec_from_file_location("_wr_gen_stubs", _HERE / "_gen_stubs.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    module.main()


def main() -> None:
    explicit = sys.argv[1] if len(sys.argv) > 1 else None
    variables_dir = _find_variables_dir(explicit)
    names = collect_variables(variables_dir)
    write_variables_py(names)
    print(f"synced {len(names)} variables from {variables_dir} -> {_VARIABLES_PY.relative_to(_REPO)}")
    _regenerate_stubs()


if __name__ == "__main__":
    main()
